//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eValorados_Web.referencia_ajuste {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="referencia_ajuste.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento almacen del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        eValorados_Web.referencia_ajuste.HelloWorldResponse HelloWorld(eValorados_Web.referencia_ajuste.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<eValorados_Web.referencia_ajuste.HelloWorldResponse> HelloWorldAsync(eValorados_Web.referencia_ajuste.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento retornardiaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornardia", ReplyAction="*")]
        eValorados_Web.referencia_ajuste.retornardiaResponse retornardia(eValorados_Web.referencia_ajuste.retornardiaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/retornardia", ReplyAction="*")]
        System.Threading.Tasks.Task<eValorados_Web.referencia_ajuste.retornardiaResponse> retornardiaAsync(eValorados_Web.referencia_ajuste.retornardiaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public eValorados_Web.referencia_ajuste.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(eValorados_Web.referencia_ajuste.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string almacen;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string motivomovimiento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string tipomovimiento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int cantidad;
        
        public HelloWorldRequestBody() {
        }
        
        public HelloWorldRequestBody(string almacen, string motivomovimiento, string tipomovimiento, int cantidad) {
            this.almacen = almacen;
            this.motivomovimiento = motivomovimiento;
            this.tipomovimiento = tipomovimiento;
            this.cantidad = cantidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public eValorados_Web.referencia_ajuste.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(eValorados_Web.referencia_ajuste.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retornardiaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="retornardia", Namespace="http://tempuri.org/", Order=0)]
        public eValorados_Web.referencia_ajuste.retornardiaRequestBody Body;
        
        public retornardiaRequest() {
        }
        
        public retornardiaRequest(eValorados_Web.referencia_ajuste.retornardiaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class retornardiaRequestBody {
        
        public retornardiaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retornardiaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="retornardiaResponse", Namespace="http://tempuri.org/", Order=0)]
        public eValorados_Web.referencia_ajuste.retornardiaResponseBody Body;
        
        public retornardiaResponse() {
        }
        
        public retornardiaResponse(eValorados_Web.referencia_ajuste.retornardiaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class retornardiaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string retornardiaResult;
        
        public retornardiaResponseBody() {
        }
        
        public retornardiaResponseBody(string retornardiaResult) {
            this.retornardiaResult = retornardiaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : eValorados_Web.referencia_ajuste.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<eValorados_Web.referencia_ajuste.ServiceSoap>, eValorados_Web.referencia_ajuste.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eValorados_Web.referencia_ajuste.HelloWorldResponse eValorados_Web.referencia_ajuste.ServiceSoap.HelloWorld(eValorados_Web.referencia_ajuste.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld(string almacen, string motivomovimiento, string tipomovimiento, int cantidad) {
            eValorados_Web.referencia_ajuste.HelloWorldRequest inValue = new eValorados_Web.referencia_ajuste.HelloWorldRequest();
            inValue.Body = new eValorados_Web.referencia_ajuste.HelloWorldRequestBody();
            inValue.Body.almacen = almacen;
            inValue.Body.motivomovimiento = motivomovimiento;
            inValue.Body.tipomovimiento = tipomovimiento;
            inValue.Body.cantidad = cantidad;
            eValorados_Web.referencia_ajuste.HelloWorldResponse retVal = ((eValorados_Web.referencia_ajuste.ServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eValorados_Web.referencia_ajuste.HelloWorldResponse> eValorados_Web.referencia_ajuste.ServiceSoap.HelloWorldAsync(eValorados_Web.referencia_ajuste.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<eValorados_Web.referencia_ajuste.HelloWorldResponse> HelloWorldAsync(string almacen, string motivomovimiento, string tipomovimiento, int cantidad) {
            eValorados_Web.referencia_ajuste.HelloWorldRequest inValue = new eValorados_Web.referencia_ajuste.HelloWorldRequest();
            inValue.Body = new eValorados_Web.referencia_ajuste.HelloWorldRequestBody();
            inValue.Body.almacen = almacen;
            inValue.Body.motivomovimiento = motivomovimiento;
            inValue.Body.tipomovimiento = tipomovimiento;
            inValue.Body.cantidad = cantidad;
            return ((eValorados_Web.referencia_ajuste.ServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eValorados_Web.referencia_ajuste.retornardiaResponse eValorados_Web.referencia_ajuste.ServiceSoap.retornardia(eValorados_Web.referencia_ajuste.retornardiaRequest request) {
            return base.Channel.retornardia(request);
        }
        
        public string retornardia() {
            eValorados_Web.referencia_ajuste.retornardiaRequest inValue = new eValorados_Web.referencia_ajuste.retornardiaRequest();
            inValue.Body = new eValorados_Web.referencia_ajuste.retornardiaRequestBody();
            eValorados_Web.referencia_ajuste.retornardiaResponse retVal = ((eValorados_Web.referencia_ajuste.ServiceSoap)(this)).retornardia(inValue);
            return retVal.Body.retornardiaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eValorados_Web.referencia_ajuste.retornardiaResponse> eValorados_Web.referencia_ajuste.ServiceSoap.retornardiaAsync(eValorados_Web.referencia_ajuste.retornardiaRequest request) {
            return base.Channel.retornardiaAsync(request);
        }
        
        public System.Threading.Tasks.Task<eValorados_Web.referencia_ajuste.retornardiaResponse> retornardiaAsync() {
            eValorados_Web.referencia_ajuste.retornardiaRequest inValue = new eValorados_Web.referencia_ajuste.retornardiaRequest();
            inValue.Body = new eValorados_Web.referencia_ajuste.retornardiaRequestBody();
            return ((eValorados_Web.referencia_ajuste.ServiceSoap)(this)).retornardiaAsync(inValue);
        }
    }
}
